### ISSUE TITLE
Bot calls everyone by my name

### ISSUE THREAD

**Issue by kaeden-crypto** [Carbowix/Cleve#3]
I asked it to call me by my name and then when someone else asked the bot, whats my name it said, my name, it can like only talk to one person at a time

**Comment by kaeden-crypto** [comment]
I asked it to call me by my name, someone else said asked the bot what their name was and it said my name meaning it can't store like multiple people's data

**Comment by Carbowix** [comment]
That's not a technical issue I should support but anyway, your problem might be because you're using the same chat ID for every user chatting with the bot. That's why it might not be able to distinguish between multiple people data. Your solution is to create your own ID system or maybe use discord's ID system to differentiate between the users. Edit the following line with your own ID and it should work.
https://github.com/Carbowix/Cleve/blob/master/util.js#L24
Otherwise, I'm not a brainshop.ai support agent.

**Comment by LcorpOfficial** [comment]
simply change uid on the line Carbowix linked in util.js to "uid: msg.author.id" for separate users per discord user ID. Uses discord.js to grab them.
