### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by soup-27** [Carbowix/Cleve#58]
 npm run start

> clevy@2.0.0 start
> node index.js

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/home/runner/Cleve/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.12.1
exit status 1


**Comment by Carbowix** [comment]
The error is pretty clear. It can't find `index.js` because it's located inside the `src` folder. So either run `npm run start` or do `cd src && node index.js`.

**Comment by soup-27** [comment]
yeah both don’t work

**Comment by Carbowix** [comment]
Can you show me your directory? What is inside `Cleve` folder. Try to see where index.js is located and let the terminal point to it using the `cd` command (should be `Cleve/src`) then do `node index.js`

**Comment by soup-27** [comment]
![IMG_7610](https://user-images.githubusercontent.com/98230243/235822836-8b336611-4bb7-4aa9-9a0a-430bde358c09.jpeg)
![IMG_7609](https://user-images.githubusercontent.com/98230243/235822837-13a91200-10a0-4b1a-b1a4-85f883bac17a.jpeg)

**Comment by Carbowix** [comment]
According to the discord.js channel, that error was due to an error in a certain version of discord.js. So I suggest that you update discord.js yourself by doing `npm install discord.js@latest` or **re-download** Cleve again and do the same installation process. I have updated the discord.js version to avoid this issue in the future.
Apologies for the inconvenience

**Comment by soup-27** [comment]
Thanks, the bot works now
