### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by PaintDEV** [Carbowix/Cleve#6]
![image](https://user-images.githubusercontent.com/79008840/119213905-e0b5ef80-baec-11eb-9bff-8c316dfdffc9.png)

what should i do?

**Comment by Carbowix** [comment]
Hello there,
This error happens due to having an old version of `discord.js`. To fix it, you need to update discord.js to the latest version via `yarn add discord.js` or `npm install discord.js --save`. Another solution, if you don't want to update your discord.js module then edit `line:81 node_modules/discord.js/src/client/ClientDataManager.js`

**Default looking**:
```js
guild.channels.set(channel.id, channel);
```

**After your edit**:
```js
if (channel !== null) guild.channels.set(channel.id, channel);
```

This was based on a [this](https://stackoverflow.com/questions/66894757/discord-js-cannot-read-property-id-of-undefined) stackoverflow question. Googling the error next time should help you tackle issues like that faster. 
If you have any more issues regarding **Cleve** then consider opening another issue.
