### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by Quak6464** [Carbowix/Cleve#67]
![Screenshot_2024-01-19-00-19-17-293_com android chrome](https://github.com/Carbowix/Cleve/assets/156640171/9abbfbe3-3f29-474a-a2e7-a21ff60007e8)
How to fix it

**Comment by Quak6464** [comment]
I check j fill every details

**Comment by Carbowix** [comment]
Hey @Quak6464,
it seems the bot can't find the `events` folder to start. It seems that the problem is that `index.js` is not in the same directory as the `events` folder. If you changed the folder structure in any way, I suggest having the folder structure like that.
![image](https://github.com/Carbowix/Cleve/assets/24420693/7f3478b0-1237-4dff-9909-f714a0b0c560)

**Comment by Quak6464** [comment]
Ok, I'll check it out.

**Comment by Carbowix** [comment]
> I can't reorder file in my host
It seems that your `index.js` is inside `home/container` while the rest of the folders could be inside `home/container/src`. You can re-upload all the files/folders inside `home/container/src/` to be in `home/container/` and it should solve your problem.

**Comment by Quak6464** [comment]
Hey buddy I am not able to solve the problem can you contact me on discord or tell me your discord tag

**Comment by Carbowix** [comment]
Hey @Quak6464,
You can join the [discord server](https://discord.gg/nntu7rgxtP), so I can help you directly more.
