### ISSUE TITLE
Env?

### ISSUE THREAD

**Issue by scramble8bit** [Carbowix/Cleve#7]
Are there anyway I can use .env instead of config.json?

**Comment by Carbowix** [comment]
I'm not planning to add support for the process environment instead of the current configuration, but you can easily add it yourself. Consider adding a file named for example: `config.env` in the current cleve folder. Then start adding the values that are in the `misc/config.json` in the `.env` with its respected form. For example:

```env
TOKEN = "YOUR_TOKEN"
STATUS_STATE = "idle"
STATUS_TYPE = "PLAYING"
STATUS_NAME = "Chat simulator"
```

Continue copying over the rest of the config like how I showed you. Then you should edit cleve's source and replace each variable that contained `config.someProperty` with its relative to in the `.env`.  For example `token` in this line, <https://github.com/Carbowix/Cleve/blob/master/index.js#L44> should be replaced with `process.env.TOKEN`. You need a little bit of experience in js in order to get it to work. After finishing the config replacements in general run `yarn add dotenv` on console then add `require('dotenv').config();` on first line of the `index.js` in cleve folder.
